name: Docker Image CI

      # es el evento , cada vez que se hace push a la rama main se ejecuta el workflow
on:
  push:
    branches: [ "main" ]
    

jobs:

  construir:
      # construye esta imagen de ubuntu
    runs-on: ubuntu-24.04
      
    steps:
      # clona el repositorio en el que esta el fichero y meterlo dentro de la imagen de ubuntu
    - name: Hacer checkout
      uses: actions/checkout@v4
      
      # hace el login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
      # fin
